services:
  fastapi:
    build:
      context: backend
    container_name: fastapi_app
    restart: always
    ports:
      - "8001:8001"
#     depends_on:
#       - postgres
#       - redis
#     environment:
#       POSTGRES_HOST: postgres
#       POSTGRES_PORT: 5432
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: passengers_db
#       REDIS_HOST: redis
#       REDIS_PORT: 6379

#   postgres:
#     image: postgres:15
#     container_name: local_postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: passengers_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   redis:
#     image: redis:7
#     container_name: local_redis
#     restart: always
#     ports:
#       - "6379:6379"

# volumes:
#   postgres_data:
